import pickle
import numpy as np
import sys, os, shutil
sys.path.append(os.getcwd()) ## this lets python find src
from blip.src.makeLISAdata import LISAdata
from blip.src.models import Model, Injection
from blip.src.fast_geometry import fast_geometry
from blip.src.utils import ensure_color_matching
import matplotlib.pyplot as plt

# constants
c = 2.99792458e8  # speed of light [m/s]

class LISA(LISAdata, Model):

    '''
    Generic class for getting data and setting up the prior space
    and likelihood. This is tuned for ISGWB analysis at the moment
    but it should not be difficult to modify for other use cases.
    '''

    def __init__(self, params, inj):
        
        # set up the LISAdata class
        LISAdata.__init__(self, params, inj)

        # Generate or get mldc or other loaded data
        if self.params['load_data']:
            self.process_external_data()
        elif self.inj['loadInj']:
            self.load_blip_injection_data()
        else:
            self.makedata()
        
        ## compute the cross/auto-channel correlations
        self.make_data_correlation_matrix()
        
        if not self.inj['inj_only']:
            # Set up the Bayes class
            print("Building Bayesian model...")
            self.Model = Model(params,inj,self.fdata,self.f0,self.tsegmid,self.rmat)
            
            # make sure matching injections/models have matching colors
            if not self.params['load_data']:
                ensure_color_matching(self.Model,self.Injection)
        
        ## if doing an injection, we also need the responses evaluated at the data frequencies for plotting/validation
        if not self.params['load_data'] and not self.inj['loadInj']:
            self.generate_inj_fdata_responses()
            self.compute_inj_fdata_spectra()
        
        # Make some simple diagnostic plots to contrast spectra
        if self.params['load_data']:
            self.plot_spectra()
        elif not self.inj['loadInj']:
            self.diag_spectra()
            
    def load_blip_injection_data(self):
        '''
        Function to load in data created via BLIP's own Injection routines, with associated Injection file.
        This is useful because we save true values, frozen spectra, etc. in addition to the raw data stream,
        so loading autogenerated data in this way allows BLIP's plotting and post-processing routines to
        return significantly more informative outputs.
        '''
        print("Loading extant BLIP-generated data from {}".format(self.inj['injdir']))
        
        with open(self.inj['injdir'] + '/injection.pickle', 'rb') as injectionfile:
            self.Injection = pickle.load(injectionfile)
        
        loaded_data = np.load(self.inj['injdir']+'/simulated_data.npz')
        
        self.timearray, self.h1, self.h2, self.h3 = loaded_data['timearray'], loaded_data['h1'], loaded_data['h2'], loaded_data['h3']
        
        # Generate lisa freq domain data from time domain data
        self.r1, self.r2, self.r3, self.fdata, self.tsegstart, self.tsegmid = self.tser2fser(self.h1, self.h2, self.h3, self.timearray)

        # Charactersitic frequency. Define f0
        fstar = c / (2*np.pi*self.armlength)
        self.f0 = self.fdata/(2*fstar)
        
    def makedata(self):

        '''
        Just a wrapper function to use the methods the LISAdata class
        to generate data. Return Frequency domain data.
        '''

        ## define the splice segment duration
        tsplice = 1e4
        ## the segments to be splices are half-overlapping
        nsplice = 2*int(self.params['dur']/tsplice) + 1
        ## arrays of segmnent start and mid times
        tsegmid = self.params['tstart'] +  (tsplice/2.0) * np.arange(nsplice) + (tsplice/2.0)
        ## Number of time-domain points in a splice segment
        Npersplice = int(self.params['fs']*tsplice)
        ## leave out f = 0
        frange = np.fft.rfftfreq(Npersplice, 1.0/self.params['fs'])[1:]
        ## the charecteristic frequency of LISA, and the scaled frequency array
        fstar = c / (2*np.pi*self.armlength)
        f0 = frange/(2*fstar)
        
        ## Build the Injection object
        print("Constructing injection...")
        self.Injection = Injection(self.params,self.inj,frange,f0,tsegmid)
        
        ## assign a couple additional universal injection attributes needed in add_sgwb_data()
        self.Injection.Npersplice = Npersplice
        self.Injection.nsplice = nsplice
        
        # Generate TDI noise
        times, self.h1, self.h2, self.h3 = self.Injection.components['noise'].gen_noise_spectrum()
        delt = times[1] - times[0]

        # Cut to required size
        N = int((self.params['dur'])/delt)
        self.h1, self.h2, self.h3 = self.h1[0:N], self.h2[0:N], self.h3[0:N]

        ## create time-domain contribution from each injection component that isn't noise
        for component in self.Injection.sgwb_component_names:
            h1_gw, h2_gw, h3_gw, times = self.add_sgwb_data(self.Injection.components[component])
            h1_gw, h2_gw, h3_gw = h1_gw[0:N], h2_gw[0:N], h3_gw[0:N]

            # Add gravitational-wave time series to noise time-series
            self.h1 = self.h1 + h1_gw
            self.h2 = self.h2 + h2_gw
            self.h3 = self.h3 + h3_gw
        

        self.timearray = times[0:N]
        if delt != (times[1] - times[0]):
            raise ValueError('The noise and signal arrays are at different sampling frequencies!')

        # Desample if we increased the sample rate for time-shifts.
        if self.params['fs'] != 1.0/delt:
            self.params['fs'] = 1.0/delt

        # Generate lisa freq domain data from time domain data
        self.r1, self.r2, self.r3, self.fdata, self.tsegstart, self.tsegmid = self.tser2fser(self.h1, self.h2, self.h3, self.timearray)

        # Charactersitic frequency. Define f0
        fstar = c / (2*np.pi*self.armlength)
        self.f0 = self.fdata/(2*fstar)
        
    def make_data_correlation_matrix(self):
        '''
        Uses the generated time-domain data series to construct a data correlation matrix.
        
        Used to be the initialization of the (now defunct) likelihoods.py
        '''
        self.r12 = np.conj(self.r1)*self.r2
        self.r13 = np.conj(self.r1)*self.r3
        self.r21 = np.conj(self.r2)*self.r1
        self.r23 = np.conj(self.r2)*self.r3
        self.r31 = np.conj(self.r3)*self.r1
        self.r32 = np.conj(self.r3)*self.r2
        self.rbar = np.stack((self.r1, self.r2, self.r3), axis=2)

        ## create a data correlation matrix
        self.rmat = np.zeros((self.rbar.shape[0], self.rbar.shape[1], self.rbar.shape[2], self.rbar.shape[2]), dtype='complex')

        for ii in range(self.rbar.shape[0]):
            for jj in range(self.rbar.shape[1]):
                self.rmat[ii, jj, :, :] = np.tensordot(np.conj(self.rbar[ii, jj, :]), self.rbar[ii, jj, :], axes=0 )

    def generate_inj_fdata_responses(self):
        '''
        A function to generate the response functions for each injection at the simulated data frequencies.
        
        This is needed to allow us to accurately plot and compare injected spectra vs. simulated data vs. recovered models.
        
        '''
        #Charactersitic frequency
        fstar = c / (2*np.pi*self.armlength)
        # define f0 = f/2f*
        f0_data = self.fdata/(2*fstar)
        fast_rx = fast_geometry(self.params)
        fast_rx.calculate_response_functions(f0_data,self.tsegmid,[self.Injection.components[cmn] for cmn in self.Injection.sgwb_component_names],self.params['tdi_lev'],plot_flag=True)
        
        return
    
    def compute_inj_fdata_spectra(self):
        '''
        A function to compute the injected spectra as evaluated at the simulated data frequencies.
        
        This is needed to allow us to accurately plot and compare injected spectra vs. simulated data vs. recovered models.
        '''
        for cmn in self.Injection.component_names:
            
            cm = self.Injection.components[cmn]
            
            #Charactersitic frequency
            fstar = 3e8/(2*np.pi*self.armlength)
            # define f0 = f/2f*
            f0_data = self.fdata/(2*fstar)
            cm.fdata = self.fdata
            ## note that for astrophysical signals we take the time-average but keep the full 3x3 correlation matrix
            if cmn == 'noise':
                Np, Na = 10**cm.injvals['log_Np'], 10**cm.injvals['log_Na']
                cm.fdata_noise = cm.instr_noise_spectrum(self.fdata,f0_data, Np, Na)
            elif hasattr(cm,"ispop") and cm.ispop:
                cm.fdata_spectra = cm.population.Sgw_true
                cm.fdata_convolved_spectra = np.mean(cm.fdata_spectra[None,None,:,None] * cm.fdata_response_mat,axis=-1)
            else:
                spec_args = [cm.truevals[parameter] for parameter in cm.spectral_parameters]
                cm.fdata_spectra = cm.compute_Sgw(self.fdata,spec_args)
                cm.fdata_convolved_spectra = np.mean(cm.fdata_spectra[None,None,:,None] * cm.fdata_response_mat,axis=-1)
        
        return
                 
    def diag_spectra(self):

        '''
        A function to do simple diagnostics. Plot the expected spectra and data.
        '''

        # ------------ Calculate PSD ------------------

        # PSD from the FFTs
        data_PSD1, data_PSD2, data_PSD3  = np.mean(np.abs(self.r1)**2, axis=1), np.mean(np.abs(self.r2)**2, axis=1), np.mean(np.abs(self.r3)**2, axis=1)

        # "Cut" to desired frequencies
        idx = np.logical_and(self.fdata >=  self.params['fmin'] , self.fdata <=  self.params['fmax'])
        psdfreqs = self.fdata[idx]

        # Get desired frequencies for the PSD
        # We want to normalize PSDs to account for the windowing
        # Also convert from doppler-shift spectra to strain spectra
        data_PSD1,data_PSD2, data_PSD3 = data_PSD1[idx], data_PSD2[idx], data_PSD3[idx]
        
        ## Get the noise component
        cmn_noise = self.Injection.components['noise']
        C_noise = cmn_noise.fdata_noise

        # Extract noise auto-power
        S1, S2, S3 = C_noise[0, 0, :], C_noise[1, 1, :], C_noise[2, 2, :]

        ## compute and save the time-averaged response-convolved spectrum for plotting, etc.
        for cmn in self.Injection.sgwb_component_names:
            cm = self.Injection.components[cmn]
            if hasattr(cm,"ispop") and cm.ispop:
                Sgw_convolved = cm.fdata_convolved_spectra ## the population spectra needs to be binned at the observed (data) frequencies in any case
            else:
                Sgw_convolved = np.mean(cm.frozen_spectra[None,None,:,None] * cm.inj_response_mat,axis=-1)
            cm.frozen_convolved_spectra = Sgw_convolved
        
        ## prep saving original PSDs
        ## load or create plot_data dict
        plot_data_path = self.params['out_dir']+'/plot_data.pickle'
        if os.path.exists(plot_data_path):
            with open(plot_data_path, 'rb') as datafile:
                plot_data = pickle.load(datafile)
                if 'injspec_data' not in plot_data.keys():
                    plot_data['injspec_data'] = {}
        else:
            plot_data = {'injspec_data':{}}
        
        ## add the full-spectrum simulated data fft to the plotdata dict
        plot_data['injspec_data']['data_psd'] = {'psdfreqs':psdfreqs,'psd1':data_PSD1,'psd2':data_PSD2,'psd3':data_PSD3}
        ## also the noise contributions
        plot_data['injspec_data']['noise_spectra'] = {'noise1':S1,'noise2':S2,'noise3':S3}
        
        plt.close()
        
        # noise multichannel plots
        
        ffilt = (self.fdata>=self.params['fmin'])*(self.fdata<=self.params['fmax'])
#        plt.loglog(psdfreqs, data_PSD1,label='Simulated Data Series PSD', alpha=0.6, lw=0.75,color='slategrey')
        if self.params['tdi_lev'] == 'michelson':
            channel_labels = ['1','2','3']
        elif self.params['tdi_lev'] == 'xyz':
            channel_labels = ['X','Y','Z']
        elif self.params['tdi_lev'] == 'aet':
            channel_labels = ['A','E','T']
        plot_data['injspec_data']['channels'] = channel_labels
        
        channel_colors = ['black','darkgrey','steelblue']
        ## flag if we need to look at CSDs also
        cross = False
        if cross:
            fig, (ax1,ax2) = plt.subplots(1,2,figsize=(15,7))
            ax_list = [ax1,ax2]
        else:
            plt.figure()
            ax1 = plt.gca()
            ax_list = [ax1]
        ax1.set_title('Instrumental Noise Autopower Spectral Density')
        for i in range(3):
            ax1.loglog(self.fdata[ffilt], C_noise[i, i, :][ffilt], label=channel_labels[i]+channel_labels[i], lw=0.75,color=channel_colors[i])
        ax1.legend()
        if cross:
            ax2.set_title('Instrumental Noise Crosspower Spectral Density')
            for i,j,k in zip([0,0,1],[1,2,2],[0,1,2]):
                ax2.loglog(self.fdata[ffilt], C_noise[i, j, :][ffilt], label=channel_labels[i]+channel_labels[j], lw=0.75,color=channel_colors[k])
            ax2.legend()
        for ax in ax_list:
            ax.set_xlabel('$f$ in Hz')
            ax.set_ylabel('PSD 1/Hz ')
            ax.set_xlim(self.params['fmin'], self.params['fmax'])
        plt.tight_layout()
        plt.savefig(self.params['out_dir'] + '/noise_multichannel.png', dpi=200)
        print('Diagnostic noise spectra plot made in ' + self.params['out_dir'] + '/noise_multichannel.png')
        
        plt.close()
        
        
        ## psd budget plot
        ffilt = (self.fdata>=self.params['fmin'])*(self.fdata<=self.params['fmax'])
        plt.loglog(psdfreqs, data_PSD1,label='Simulated Data Series PSD', alpha=0.6, lw=0.75,color='slategrey')
        plt.loglog(self.fdata[ffilt], C_noise[0, 0, :][ffilt], label='Instrumental Noise ({} Autopower)'.format(channel_labels[0]+channel_labels[0]), lw=0.75,color='dimgrey')

        
        ymins = []
        ymeds = []
        ywmeds = []
        ydevs = []
        ylim_flag = False
        for component_name in self.Injection.sgwb_component_names:
            S1_gw = self.Injection.plot_injected_spectra(component_name,fs_new='data',convolved=True,legend=True,channels='11',return_PSD=True,lw=0.75,color=self.Injection.components[component_name].color)
            S1_gw_filt = S1_gw[ffilt]
            plot_data['injspec_data'][component_name] = {'S1_gw':S1_gw_filt}
            plot_data['injspec_data'][component_name]['f_filt'] = self.fdata[ffilt]
            log_S1_gw = np.log10(S1_gw_filt[np.nonzero(S1_gw_filt)])
            log_bin_sizes = np.log10(self.fdata[ffilt][np.nonzero(S1_gw_filt)])[1:] - np.log10(self.fdata[ffilt][np.nonzero(S1_gw_filt)])[:-1]
            ave_bin_val = (log_S1_gw[1:] + log_S1_gw[:-1])/2
            weighted_ymed = np.sum(log_bin_sizes*ave_bin_val/np.sum(log_bin_sizes))
            ymins.append(np.min(log_S1_gw))
            ymeds.append(np.median(log_S1_gw))
            ywmeds.append(weighted_ymed)
            ydevs.append(np.std(log_S1_gw))
            ylim_flag = True
            S2_gw, S3_gw = self.Injection.compute_convolved_spectra(component_name,fs_new='data',channels='22'), self.Injection.compute_convolved_spectra(component_name,fs_new='data',channels='33')
            S1, S2, S3 = S1+S1_gw, S2+S2_gw, S3+S3_gw
        
        plt.loglog(self.fdata[ffilt], S1[ffilt], label='Simulated Total spectrum', lw=0.75,color='cadetblue')

        ## set plot limits, with dynamic scaling for the y-axis to handle spectra with cutoffs, etc.
        if ylim_flag:
            ylows = [ywmed_i - ydev_i for ywmed_i,ydev_i in zip(ywmeds,ydevs)]
            ylow_min = np.min(ylows)
            plt.ylim(bottom=10**(ylow_min-1))
            ## save for plotting the results with plotmaker
            self.Injection.plot_ymin = 10**(ylow_min-1)

        plt.legend(loc='upper right')
        plt.xlabel('$f$ in Hz')
        plt.ylabel('PSD 1/Hz ')
        plt.xlim(self.params['fmin'], self.params['fmax'])
        plt.savefig(self.params['out_dir'] + '/psd_budget.png', dpi=200)
        print('Diagnostic spectra plot made in ' + self.params['out_dir'] + '/psd_budget.png')
        plt.close()


        plt.loglog(self.fdata, S3, label='required',color='mediumvioletred')
        plt.loglog(psdfreqs, data_PSD3,label='PSD, data', alpha=0.6,color='slategrey')
        plt.xlabel('$f$ in Hz')
        plt.ylabel('PSD 1/Hz ')
        plt.legend()
        plt.grid(linestyle=':',linewidth=0.5 )
        plt.xlim(self.params['fmin'], self.params['fmax'])
        ## avoid plot squishing due to signal spectra with cutoffs, etc.
        if len(ymins) > 0:
            ymin = np.min(ymins)
            if ymin < 1e-43:
                plt.ylim(bottom=1e-43)
        
        plt.savefig(self.params['out_dir'] + '/diag_psd.png', dpi=200)
        print('Diagnostic spectra plot made in ' + self.params['out_dir'] + '/diag_psd.png')
        plt.close()


        ## lets also plot psd residue.        
        rel_res_mean = (data_PSD3 - S3)/S3

        plt.semilogx(self.fdata, rel_res_mean , label='relative mean residue',color='slategrey')
        plt.xlabel('f in Hz')
        plt.ylabel(' Rel. residue')
        plt.ylim([-1.50, 1.50])
        plt.legend()
        plt.grid()
        plt.xlim(self.params['fmin'], self.params['fmax'])

        plt.savefig(self.params['out_dir'] + '/res_psd.png', dpi=200)
        print('Residue spectra plot made in ' + self.params['out_dir'] + '/res_psd.png')
        plt.close()
#        
        # cross-power diag plots. We will only do 12. IF TDI=XYZ this is S_XY and if TDI=AET
        # this will be S_AE
        
        ii, jj = 2,0
        IJ = str(ii+1)+str(jj+1)
        
        Sx = C_noise[ii,jj,:]
        
        ymins = []
        iymins = []
        for component_name in self.Injection.sgwb_component_names:
            if component_name != 'noise':
                Sx_gw = self.Injection.compute_convolved_spectra(component_name,fs_new='data',channels=IJ) + self.Injection.compute_convolved_spectra(component_name,fs_new='data',channels=IJ,imaginary=True)
                ymins.append(np.real(Sx_gw).min())
                iymins.append(np.imag(Sx_gw).min())
                Sx = Sx + Sx_gw
       
        CSDx = np.mean(np.conj(self.rbar[:, :, ii]) * self.rbar[:, :, jj], axis=1)

        plt.subplot(2, 1, 1)
        if len(Sx.shape) == 1:
            plt.loglog(self.fdata, np.abs(np.real(Sx)), label='Re(Required ' + str(ii+1) + str(jj+1) + ')',color='mediumvioletred')
        else:
            plt.loglog(self.fdata, np.mean(np.abs(np.real(Sx)),axis=1), label='Re(Required ' + str(ii+1) + str(jj+1) + ')',color='mediumvioletred')
        plt.loglog(psdfreqs, np.abs(np.real(CSDx)) ,label='Re(CSD' + str(ii+1) + str(jj+1) + ')', alpha=0.6,color='slategrey')
        plt.xlabel('f in Hz')
        plt.ylabel('Power in 1/Hz')
        plt.legend()
        plt.ylim([1e-44, 5e-40])
        plt.xlim(self.params['fmin'], self.params['fmax'])
        plt.grid()

        plt.subplot(2, 1, 2)
        if len(Sx.shape) == 1:
            plt.loglog(self.fdata, np.abs(np.imag(Sx)), label='Im(Required ' + str(ii+1) + str(jj+1) + ')',color='mediumvioletred')
        else:
            plt.loglog(self.fdata, np.mean(np.abs(np.imag(Sx)),axis=1), label='Im(Required ' + str(ii+1) + str(jj+1) + ')',color='mediumvioletred')

        plt.loglog(psdfreqs, np.abs(np.imag(CSDx)) ,label='Im(CSD' + str(ii+1) + str(jj+1) + ')', alpha=0.6,color='slategrey')
        plt.xlabel('f in Hz')
        plt.ylabel(' Power in 1/Hz')
        plt.legend()
        plt.xlim(self.params['fmin'], self.params['fmax'])
        plt.ylim([1e-44, 5e-40])
        plt.grid()
        plt.savefig(self.params['out_dir'] + '/diag_csd_' + str(ii+1) + str(jj+1) + '.png', dpi=200)
        print('Diagnostic spectra plot made in ' + self.params['out_dir'] + '/diag_csd_' + str(ii+1) + str(jj+1) + '.png')
        plt.close()
        
        
        ## save fit data
        if os.path.exists(plot_data_path):
            ## move to temp file
            temp_file = plot_data_path + ".temp"
            with open(temp_file, "wb") as datafile:
                pickle.dump(plot_data,datafile)
            shutil.move(temp_file, plot_data_path)
        else:
            with open(plot_data_path, 'wb') as datafile:
                plot_data = pickle.dump(plot_data,datafile)
        
    def plot_spectra(self):
        '''
        A function to make a plot of the data spectrum. For use with external (non-autogenerated) data, where we cannot calculate the intrinsic components.
        '''
    
        # PSD from the FFTs
        data_PSD1, data_PSD2, data_PSD3  = np.mean(np.abs(self.r1)**2, axis=1), np.mean(np.abs(self.r2)**2, axis=1), np.mean(np.abs(self.r3)**2, axis=1)
    
        # "Cut" to desired frequencies
        idx = np.logical_and(self.fdata >=  self.params['fmin'] , self.fdata <=  self.params['fmax'])
        psdfreqs = self.fdata[idx]
    
        # Get desired frequencies for the PSD
        data_PSD1,data_PSD2, data_PSD3 = data_PSD1[idx], data_PSD2[idx], data_PSD3[idx]
        
        plt.loglog(psdfreqs, data_PSD1,label='PSD (1)', alpha=0.6, color='slategrey')
        plt.loglog(psdfreqs, data_PSD2,label='PSD (2)', alpha=0.6, color='rosybrown')
        plt.loglog(psdfreqs, data_PSD3,label='PSD (3)', alpha=0.6, color='mediumseagreen')
        plt.xlabel('$f$ in Hz')
        plt.ylabel('PSD 1/Hz ')
        plt.legend()
        plt.grid(linestyle=':',linewidth=0.5 )
        plt.xlim(self.params['fmin'], self.params['fmax'])
    
        plt.savefig(self.params['out_dir'] + '/data_psd.png', dpi=200)
        print('Data spectra plot made in ' + self.params['out_dir'] + '/data_psd.png')
        plt.close()

