#!/bin/env python3

import pickle
import numpy as np
import sys, os, shutil, subprocess
sys.path.append(os.getcwd()) ## this lets python find src
from blip.src.lisa import LISA
from blip.src.emcee_engine import emcee_engine
from blip.src.numpyro_engine import numpyro_engine
from blip.src.dynesty_engine import dynesty_engine
from blip.src.eryn_engine import eryn_engine
from blip.tools.SetRandomState import SetRandomState as setrs
from blip.tools.plotmaker import cornermaker
from blip.tools.plotmaker import mapmaker
from blip.tools.plotmaker import fitmaker
from blip.tools.input_handler import load_input
from multiprocessing import Pool
import time


def blip(paramsfile='params.ini',resume=False):
    '''
    The main workhorse of the bayesian pipeline.

    Input:
    Params File

    Output: Files containing evidence and pdfs of the parameters
    '''
    
    params, inj = load_input(paramsfile=paramsfile)

    # Fix random seed
    if params['FixSeed']:
        seed = params['seed']
        randst = setrs(seed)
    else:
        if params['checkpoint']:
            raise TypeError("Checkpointing without a fixed seed is not supported. Set 'FixSeed' to true and specify 'seed'.")
        if resume:
            raise TypeError("Resuming from a checkpoint requires re-generation of data, so the random seed MUST be fixed.")
        randst = None

    if not resume:
        # Make directories, copy stuff
        # Make output folder
        subprocess.call(["mkdir", "-p", params['out_dir']])
    
        # Copy the params file to outdir, to keep track of the parameters of each run.
        subprocess.call(["cp", paramsfile, params['out_dir']])
        
        # Initialize lisa class
        lisa =  LISA(params, inj)
        
        ## save the Model and Injection as needed
        
        ## the Injection is massive, so discard the responses we no longer need
        ## saving & discarding now, as opposed to at the end of the run also saves space in the checkpoint files.
        if not params['load_data']:
            ## save Injection
            for cmn in lisa.Injection.component_names:
                if hasattr(lisa.Injection.components[cmn],'response_mat'):
                    del lisa.Injection.components[cmn].response_mat
                if hasattr(lisa.Injection.components[cmn],'summ_response_mat'):
                    del lisa.Injection.components[cmn].summ_response_mat
                if hasattr(lisa.Injection.components[cmn],'inj_response_mat'):
                    del lisa.Injection.components[cmn].inj_response_mat
            with open(params['out_dir'] + '/injection.pickle', 'wb') as outfile:
                pickle.dump(lisa.Injection, outfile)
            print("Saved Injection to "+params['out_dir']+"/injection.pickle")
            
            ## also save the injected skymaps for later use
            lisa.Injection.extract_and_save_skymap_data()
            
            ## save generated data
            np.savez_compressed(params['out_dir']+'/simulated_data.npz',timearray=lisa.timearray,h1=lisa.h1,h2=lisa.h2,h3=lisa.h3)
            print("Saved strain time series to "+params['out_dir']+"/simulated_data.npz")
            ## Data generation is complete. Exit if only performing injection and data simulation.
            if inj['inj_only']:
                print("Simulation and generation of LISA data is complete and inj_only flag is set to True. Saving configuration and exiting...")
                # Save parameters as a pickle
                with open(params['out_dir'] + '/config.pickle', 'wb') as outfile:
                    pickle.dump(params, outfile)
                    pickle.dump(inj, outfile)
                
                return
        
        ## the Model tends to be more lightweight
        with open(params['out_dir'] + '/model.pickle', 'wb') as outfile:
            pickle.dump(lisa.Model, outfile)
        print("Saved Model to "+params['out_dir']+"/model.pickle")
        
        # Also save the config so we can load and use our simulated data if the run fails during sampling
        with open(params['out_dir'] + '/config.pickle', 'wb') as outfile:
            pickle.dump(params, outfile)
            pickle.dump(inj, outfile)

        print("Generating sampling engine...")
    else:
        print("Resuming a previous analysis. Reloading data and sampler state...")

    if params['sampler'] == 'dynesty':
        # Create engine
        if not resume:
            # multiprocessing
            if params['nthread'] > 1:
                pool = Pool(params['nthread'])
            else:
                pool = None
            engine, parameters = dynesty_engine().define_engine(lisa, params, nlive, params['nthread'], randst, pool=pool)    
        else:
            pool = None
            if params['nthread'] > 1:
                print("Warning: Nthread > 1, but multiprocessing is not supported when resuming a run. Pool set to None.")
                ## To anyone reading this and wondering why:
                ## The pickle calls used by Python's multiprocessing fail when trying to run the sampler after saving/reloading it.
                ## This is because pickling the sampler maps all its attributes to their full paths;
                ## e.g., dynesty_engine.isgwb_prior is named as src.dynesty_engine.dynesty_engine.isgwb_prior
                ## BUT the object itself is still e.g. <function dynesty_engine.isgwb_prior at 0x7f8ebcc27130>
                ## so we get an error like
                ## _pickle.PicklingError: Can't pickle <function dynesty_engine.isgwb_prior at 0x7f8ebcc27130>: \
                ##                        it's not the same object as src.dynesty_engine.dynesty_engine.isgwb_prior
                ## See e.g. https://stackoverflow.com/questions/1412787/picklingerror-cant-pickle-class-decimal-decimal-its-not-the-same-object
                ## After too much time and sanity spent trying to fix this, I have admitted defeat.
                ## Feel free to try your hand -- maybe you're the chosen one. Good luck.
                
            engine, parameters = dynesty_engine.load_engine(params,randst,pool)
        ## run sampler
        if params['checkpoint']:
            checkpoint_file = params['out_dir']+'/checkpoint.pickle'
            t1 = time.time()
            post_samples, logz, logzerr = dynesty_engine.run_engine_with_checkpointing(engine,parameters,params['checkpoint_interval'],checkpoint_file,step=200)
            t2= time.time()
            print("Elapsed time to converge: {} s".format(t2-t1))
        else:
            t1 = time.time()
            post_samples, logz, logzerr = dynesty_engine.run_engine(engine)
            t2= time.time()
            print("Elapsed time to converge: {} s".format(t2-t1))
        if params['nthread'] > 1:
            engine.pool.close()
            engine.pool.join()
        # Save posteriors to file
        np.savetxt(params['out_dir'] + "/post_samples.txt",post_samples)
        np.savetxt(params['out_dir'] + "/logz.txt", logz)
        np.savetxt(params['out_dir'] + "/logzerr.txt", logzerr)

    elif params['sampler'] == 'emcee':
        # multiprocessing
        if params['nthread']>1:
            pool=Pool(params['nthread'])
        else:
            pool=None

        # Create engine
        engine, parameters, init_samples = emcee_engine.define_engine(lisa.Model, nlive, randst, pool=pool)
        unit_samples, post_samples = emcee_engine.run_engine(engine, lisa.Model, init_samples,params['Nburn'],params['Nsamples'])

        # Save posteriors to file
        np.savetxt(params['out_dir'] + "/unit_samples.txt",unit_samples)
        np.savetxt(params['out_dir'] + "/post_samples.txt",post_samples)

    elif params['sampler'] == 'numpyro':
        ## create engine
        Ntotal = params['Nsamples']
        if not resume:
            ## without checkpointing, set up the engine to run for Nsamples samples
            ## with checkpointing, set it up to run for checkpoint_interval samples (and set the starting chain to None)
            if params['checkpoint'] and params['checkpoint_at']=='interval':
                Nrun = params['checkpoint_interval']
            else:
                Nrun = Ntotal
            
            ## set initial chain to None
            chain = None
            
            if params['N_GPU'] > 0:
                use_gpu = True
            else:
                use_gpu = False
            engine, parameters, rng_key = numpyro_engine.define_engine(lisa, params['Nburn'], Nrun, params['nthread'], params['show_progress'], params['seed'], gpu=use_gpu)
            lisaModel = lisa.Model
            
        else:
            resume_file = params['out_dir']+'/checkpoint.pickle'
            engine, rng_key, chain = numpyro_engine.load_engine(resume_file)
            with open(params['out_dir'] + '/model.pickle', 'rb') as modfile:
                lisaModel = pickle.load(modfile)
            parameters = lisaModel.parameters
            
            ## check to see whether the run has already finished
            if chain is None:
                N_current = 0
            else:
                N_current = len(chain['theta_transformed'][0])
            
            ## additional samples
            if params['additional_samples'] is not None:
                if N_current < params['Nsamples']:
                    print("WARNING: {} additional samples were requested, but the original run isn't finished ({}/{} samples remaining)".format(params['additional_samples'],params['Nsamples'],params['Nsamples']))
                    print("WARNING: Disregarding and continuing the original run...")
                else:
                    print("Run was previously completed and {} additional samples have been requested. Resuming chain sampling from final state...".format(params['additional_samples']))
                    ## new total = old total + additional
                    Ntotal = N_current + params['additional_samples']
                    ## if not sampling in N=checkpoint_interval chunks, set the requested # of samples
                    if params['checkpoint_at'] != 'interval':
                        engine.num_samples = params['additional_samples']
            ## if we're not doing additional samples and the run is over, raise a helpful error.
            elif N_current==params['Nsamples']:
                raise ValueError("Run was resumed but has already finished. If you want to continue adding samples to the chain, specify additional_samples=[N desired] in the run directory params file before resuming.")

        ## run sampler
        if params['checkpoint']:
            checkpoint_file = params['out_dir']+'/checkpoint.pickle'
            t1 = time.time()
            post_samples = numpyro_engine.run_engine_with_checkpointing(engine,lisaModel,rng_key,chain,checkpoint_file,Ntotal,params['checkpoint_at'],resume=resume)
            t2= time.time()
            print("Elapsed time to converge: {} s".format(t2-t1))
        else:
            t1 = time.time()
            post_samples = numpyro_engine.run_engine(engine,lisa,rng_key)
            t2= time.time()
            print("Elapsed time to converge: {} s".format(t2-t1))
        ## save chain
        np.savetxt(params['out_dir'] + "/post_samples.txt",post_samples)
    
    elif params['sampler'] == 'eryn':
        engine, parameters, init_samples = eryn_engine.define_engine(lisa, params['nwalkers'])
        post_samples = eryn_engine.run_engine(engine, params['nsteps'], init_samples)
        post_samples = post_samples.reshape(-1, lisa.Model.Npar)
        np.save(params['out_dir'] + "/post_samples.npy", post_samples)

    else:
        raise TypeError('Unknown sampler model chosen. Only dynesty, numpyro, eryn, & emcee are supported')
    
#    
    ## Safely re-save the config pickle, now with the model parameters
    temp_file = params['out_dir'] + '/config.pickle' + ".temp"
    with open(temp_file, "wb") as outfile:
        pickle.dump(params, outfile)
        pickle.dump(inj, outfile)
        pickle.dump(parameters, outfile)
    shutil.move(temp_file, params['out_dir'] + '/config.pickle')
       
    print("\nMaking posterior Plots ...")
    ## reload the Model and Injection if needed
    if not resume:
        plotting_Model = lisa.Model
        plotting_Injection = lisa.Injection
    else:
        ## grab the model and injection
        with open(params['out_dir'] + '/model.pickle', 'rb') as modelfile:
            plotting_Model = pickle.load(modelfile)
        if not params['load_data']:
            with open(params['out_dir'] + '/injection.pickle', 'rb') as injectionfile:
                plotting_Injection = pickle.load(injectionfile)
    
    if not params['load_data']:
        cornermaker(post_samples, params, parameters, inj, plotting_Model, Injection=plotting_Injection)
    else:
        cornermaker(post_samples, params, parameters, inj, plotting_Model)
    if plotting_Model.Npar >= 10:
        print("\n")
        print("WARNING: High Model N_parameters detected ({}). Corner plot may be crowded. Try running plotmaker.py and specifying the 'cornersplit' argument via".format(plotting_Model.Npar))
        print("python3 ./blip/tools/plotmaker.py {} --cornersplit type".format(params['out_dir']))
        print("or")
        print("python3 ./blip/tools/plotmaker.py {} --cornersplit submodel".format(params['out_dir']))
        print("\n")
    if not params['load_data']:
        fitmaker(post_samples, params, parameters, inj, plotting_Model, plotting_Injection)
    else:
        fitmaker(post_samples, params, parameters, inj, plotting_Model)

    ## make a map if there is a map to be made
    if np.any([plotting_Model.submodels[sm_name].has_map for sm_name in plotting_Model.submodel_names]):
        if 'healpy_proj' in params.keys():
            mapmaker(post_samples, params, parameters, plotting_Model, coord=params['healpy_proj'], cmap=params['colormap'])
        else:
            mapmaker(post_samples, params, parameters, plotting_Model, cmap=params['colormap'])
        
    

if __name__ == "__main__":

    if len(sys.argv) != 2:
        if sys.argv[2] == 'resume':
            blip(sys.argv[1],resume=True)
        else:
            raise ValueError('Provide (only) the params file as an argument')
    else:
        blip(sys.argv[1])
